---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: crowdsec-charts
  namespace: flux-system
spec:
  interval: 2h
  timeout: 3m
  url: https://crowdsecurity.github.io/helm-charts