apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bjw-s.yaml
  - cloudnative-pg.yaml
  - descheduler.yaml
  - eraser.yaml
  - external-dns.yaml
  - external-secrets.yaml
  - fairwinds.yaml
  - grafana.yaml
  - jetstack.yaml
  - kubereboot.yaml
  - kubernetes-dashboard.yaml
  - longhorn.yaml
  - lwolf.yaml
  - metallb.yaml
  - prometheus-community.yaml
  - stakater.yaml
  - traefik-charts.yaml