apiVersion: batch/v1
kind: CronJob
metadata:
  name: outline-scheduled-job
  namespace: home
spec:
  schedule: "0 1 * * *"  # Run daily at 1am
  timeZone: ${TIMEZONE}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: outline-curl
            image: curlimages/curl:8.18.0@sha256:d94d07ba9e7d6de898b6d96c1a072f6f8266c687af78a74f380087a0addf5d17
            command: ["/bin/sh", "-c"]
            args:
            - |
              curl "https://notes.vember31.xyz/api/cron.daily?token=$(UTILS_SECRET)"

            env:
            - name: UTILS_SECRET
              valueFrom:
                secretKeyRef:
                  name: outline-secret
                  key: UTILS_SECRET

          restartPolicy: OnFailure