---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./app-template-testing.yaml
  - ./app-template.yaml
  - ./cilium.yaml
  - ./dragonfly-operator.yaml
  - ./flux-instance.yaml
  - ./flux-operator.yaml
  - ./node-feature-discovery.yaml