---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: cilium
        group: internal-backend
        url: "tcp://hubble-relay.kube-system.svc.cluster.local:80"
        interval: 1m
        conditions:
          - "[CONNECTED] == true"
        alerts:
          - type: discord
            send-on-resolved: true
            failure-threshold: 2
            minimum-reminder-interval: "3h"
