---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "hubble-gatus-ep"
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: "hubble"
        group: internal
        url: "https://${GATUS_SUBDOMAIN:-hubble}.local.${SECRET_DOMAIN}${GATUS_PATH:-/}"
        interval: 1m
        client:
          dns-resolver: tcp://${BLOCKY_IP}:53
        conditions:
          - "[STATUS] == ${GATUS_STATUS:-200}"
        alerts:
          - type: discord
            send-on-resolved: true
            failure-threshold: 2
            minimum-reminder-interval: "3h"