---
- Development:
    - Home-Ops Repo:
        - icon: si-github
          href: https://github.com/vember31/home-ops
          description: Kubernetes cluster hosted on Github
    - Gitlab CI/CD:
        - icon: si-gitlab
          href: https://gitlab.com/vember31/external-secrets/-/settings/ci_cd
          description: Storage for CI/CD Variables
    - Kubesearch:
        - icon: si-kubernetes
          href: https://kubesearch.dev/
          description: Innovation through imitation
    - Cloudflare:
        - icon: si-cloudflare
          href: https://dash.cloudflare.com/
          description: Domain & DNS management

- Providers:
    - IPTorrents:
        - abbr: IPT
          href: https://iptorrents.com
    - BroadcasTheNet:
        - abbr: BTN
          href: https://broadcasthe.net
    - TorrentLeech:
        - abbr: TL
          href: https://torrentleech.org
    - Audionews:
        - abbr: AN
          href: https://audionews.org

- Social:
    - Amazon:
        - icon: si-amazon
          href: https://amazon.com
          description: Amazon
    - Soundcloud:
        - icon: si-soundcloud
          href: https://soundcloud.com
          description: SoundCloud

- Weather:
    - MerryWeather:
        - icon: mdi-weather-lightning
          href: https://merrysky.net/forecast/{{HOMEPAGE_VAR_LATITUDE}},{{HOMEPAGE_VAR_LONGITUDE}}
    - MSN Weather:
        - icon: mdi-weather-night-partly-cloudy
          href: https://www.msn.com/en-us/weather
    - NWS Area Forecast Discussion:
        - icon: mdi-weather-cloudy-alert
        - href: https://forecast.weather.gov/product.php?site={{HOMEPAGE_VAR_NWS_ISSUER}}&issuedby={{HOMEPAGE_VAR_NWS_ISSUER}}&product=AFD