---
title: Home Dashboard
useEqualHeights: true
headerStyle: clean
language: en
target: _self
hideErrors: false
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
  provider: google
providers:
  longhorn:
    url: http://longhorn-frontend.storage.svc.cluster.local
layout:
  Calendar:
    style: column
  Status:
    style: column
  Downloads:
    style: row
    columns: 3
  Media:
    style: row
    columns: 4
  Infrastructure:
    style: row
    columns: 4
  Storage:
    style: row
    columns: 4
  Monitoring:
    style: row
    columns: 4
  Networking:
    style: column
  Home:
    style: column
  Resources:
    style: column
  Security:
    style: column
