---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name **SECRETNAME**

spec:
  secretStoreRef:
    name: gitlab-secret-store
    kind: ClusterSecretStore  # or ClusterSecretStore

  refreshInterval: "1h"
  target:
    name: *name
    creationPolicy: 'Owner'

  data:
    - secretKey: &key1 #key that will be part of the secret
      remoteRef:
        key: *key1 #key on Gitlab

    - secretKey: &key2 #key that will be part of the secret
      remoteRef:
        key: *key2 #key on Gitlab

# or use the below
  dataFrom:
    - extract:
        key: [keyname] #key on gitlab