---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tracearr
spec:
  secretStoreRef:
      name: gitlab-secret-store
      kind: ClusterSecretStore
  target:
    name: tracearr-secret
    template:
      engineVersion: v2
      data:
        # Tracearr app
        COOKIE_SECRET: "{{ .TRACEARR_COOKIE_SECRET }}"
        DATABASE_URL: |-
          postgresql://{{ .TRACEARR_POSTGRES_USER }}:{{ .TRACEARR_POSTGRES_PASSWORD }}@postgres-17-rw.database.svc.cluster.local:5432/tracearr
        JWT_SECRET: "{{ .TRACEARR_JWT_SECRET }}"
        MAXMIND_LICENSE_KEY: "{{ .TRACEARR_MAXMIND_LICENSE_KEY }}"
        REDIS_URL: |-
          redis+sentinel://redis-0:26379,redis-1:26379,redis-2:26379,redis-3:26379,redis-4:26379/redis-master

        # Postgres Init
        INIT_POSTGRES_DBNAME: tracearr
        INIT_POSTGRES_HOST: postgres-17-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .TRACEARR_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .TRACEARR_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

  dataFrom:
    - extract:
        key: cloudnativepg
    - extract:
        key: tracearr