---
# true or false
sonarrEnabled: true
radarrEnabled: true
whisparrEnabled: false
readarrEnabled: false
lidarrEnabled: false

sonarr:
  sonarr:
    base_url: http://sonarr.downloads.svc.cluster.local:8989
    api_key: !env SONARR_API_KEY

    # Media Naming Configuration
    media_naming:
      series: default
      season: default
      episodes:
        rename: true
        standard: default
        daily: default
        anime: default

    # Root Folder Setup
    root_folders:
      - /media/tv
      - /media2/tv

    # Quality definition sizes
    quality_definition:
      qualities:
        - quality: "HDTV-720p"
          min: 3
          preferred: 11.7
          max: 28
        - quality: "WEBRip-720p"
          min: 3
          preferred: 11.7
          max: 28
        - quality: "WEBDL-720p"
          min: 3
          preferred: 11.7
          max: 28
        - quality: "Bluray-720p"
          min: 3
          preferred: 11.7
          max: 28
        - quality: "HDTV-1080p"
          min: 4
          preferred: 23
          max: 65
        - quality: "WEBRip-1080p"
          min: 4
          preferred: 23
          max: 65
        - quality: "WEBDL-1080p"
          min: 4
          preferred: 23
          max: 65
        - quality: "Bluray-1080p"
          min: 4
          preferred: 23
          max: 65

    # (experimental) Manage download clients
    download_clients:
      data:
        - name: "qBittorrent"
          type: qbittorrent
          enable: true
          priority: 1
          remove_completed_downloads: false
          remove_failed_downloads: false
          tags: []
          fields:
            host: qbittorrent
            port: 8080
            use_ssl: false
            url_base: /
            username: admin
            password: {{ .QBITTORRENT_PASSWORD }}
            tv_category: sonarr
            tv_imported_category: sonarr-complete
      update_password: true
      delete_unmanaged:
        enabled: true
        ignore: []

      # Global download client configuration
      config:
        # download_client_working_folders: ""
        enable_completed_download_handling: true
        auto_redownload_failed: false
        auto_redownload_failed_from_interactive_search: true

radarr:
  radarr:
    base_url: http://radarr.downloads.svc.cluster.local:7878
    api_key: !env RADARR_API_KEY

    # Media Naming Configuration
    media_naming:
      folder: default
      movie:
        rename: true
        standard: standard

    # Root Folder Setup
    root_folders:
      - /media/movies
      - /media2/movies

    # Quality definition sizes
    quality_definition:
      qualities:
        - quality: "HDTV-720p"
          min: 0
          preferred: 18
          max: 34
        - quality: "WEBRip-720p"
          min: 0
          preferred: 18
          max: 34
        - quality: "WEBDL-720p"
          min: 0
          preferred: 18
          max: 34
        - quality: "Bluray-720p"
          min: 0
          preferred: 18
          max: 34
        - quality: "HDTV-1080p"
          min: 0
          preferred: 25
          max: 42
        - quality: "WEBRip-1080p"
          min: 0
          preferred: 25
          max: 42
        - quality: "WEBDL-1080p"
          min: 0
          preferred: 25
          max: 42
        - quality: "Bluray-1080p"
          min: 0
          preferred: 25
          max: 42

    # (experimental) Manage download clients
    download_clients:
      data:
        - name: "qBittorrent"
          type: qbittorrent
          enable: true
          priority: 1
          remove_completed_downloads: false
          remove_failed_downloads: false
          tags: []
          fields:
            host: qbittorrent
            port: 8080
            use_ssl: false
            url_base: /
            username: admin
            password: {{ .QBITTORRENT_PASSWORD }}
            movie_category: radarr
            movie_imported_category: radarr-complete
      update_password: true
      delete_unmanaged:
        enabled: true
        ignore: []
      # Global download client configuration
      config:
        # download_client_working_folders: ""
        enable_completed_download_handling: true
        auto_redownload_failed: false
        auto_redownload_failed_from_interactive_search: true
        check_for_finished_download_interval: 1